processor:
  build: .
  links:
    - test_db:db
  environment:
    VIP_DP_SQS_REGION: US_WEST_2
  command: lein test :postgres
test_db:
  image: postgres:9.4.1
  ports:
    - "5432"
  environment:
    POSTGRES_USER: data_processor_test
    POSTGRES_PASSWORD: data-processor-test
    POSTGRES_DATABASE: data_processor_test_db
